#!/bin/sh     

if [ $# -ne 1 ] ; then
    echo Usage: $0 absdir
    exit
fi
topdir=$1
if [[ $topdir == .* ]]; then
    topdir=`pwd`${topdir#.}
    echo $topdir
fi

md5sum_record()
{
    cd $1
    files=`ls | tr " " "\?"`
    for current_file in $files; do
        pathfile=${current_file/\?/\ }
        if [ -d "$1/$pathfile" ]; then
            md5sum_record "$1/$pathfile"
        else
            md5sum "$1/$pathfile"
        fi
    done
}

#---------------
#  Main program
#---------------
if [ -f $topdir ];then
    md5sum $topdir
else
    cd $topdir
    md5sum_record $topdir
fi
